module(
    name = "git_override_test",
    version = "0.0.1",
    compatibility_level = 1,
)

bazel_dep(name = "rules_cc", version = "0.1.0")
bazel_dep(name = "rules_python", version = "1.0.0")

git_override(module_name = "rules_cc",
             commit = "15c158886752ceddb4d6bac17e7b5a74feab53b5",
             remote = "https://github.com/bazelbuild/rules_cc")
